services:
    database:
        image: 'mysql:5.6'
        environment:
          MYSQL_DATABASE: 'shopping-list'
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: 'password'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: '5s'
            retries: 5
            start_period: '30s'
        volumes:
            - 'database_data:/var/lib/mysql:rw'

volumes:
    database_data: ~