version: '3.4'

services:
  database:
    image: mysql:5.6
    volumes:
      - db-data:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=shopping-list
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - target: 3306
        protocol: tcp

volumes:
  db-data: {}
