# https://taskfile.dev

version: 3

tasks:
    default:
        cmds:
            - task --list

    start:
        desc: Start the Symfony server and open local browser, then show logs
        cmds:
            - symfony server:start
            - symfony open:local
            - symfony server:log

    fixtures:
        desc: Load fixtures with exclusions
        cmds:
            - symfony console doctrine:fixtures:load -n --purge-exclusions shopping_list

    stop:
        desc: Stop the Symfony server
        cmds:
            - symfony server:stop