controllers:
    resource: '../../src/Controller/'
    type: 'annotation'

kernel:
    resource: '../../src/Kernel.php'
    type: 'annotation'

homepage:
    path: '/'
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction'
        template: 'homepage.html.twig'
