controllers:
    resource:
        path: '../src/Controller/'
        namespace: 'App\Controller'
    type: 'attribute'

homepage:
    path: '/'
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction'
        template: 'homepage.html.twig'