controllers:
    resource:
        path: '../src/Controller/'
        namespace: 'App\Controller'
    type: 'attribute'

sort_tab:
    path: '/'
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction'
        template: 'sort.html.twig'

recipe_tab:
    path: '/recipe'
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction'
        template: 'recipe.html.twig'